#!/usr/bin/env bash

# Adiciona o arquivo measurements para o hdfs do hadoop
echo Iniciando insercao de measurements no hdfs
hadoop fs -put measurements.txt
echo Finalizada insercao de measurements no hdfs

# Adiciona o arquivo sensor-location para o hdfs do hadoop
echo Iniciando insercao de sensor-location no hdfs
hadoop fs -put sensor-location.txt
echo Finalizada insercao de sensor-location no hdfs

# Cria um novo arquivo que junta as informacoes dos dois arquivos, esse arquivo sera criado no hdfs com o nome measurements-vs-sensor-location
echo Iniciando job mapreduce responsavel por juntar os dados
./join.sh
echo Finalizado job mapreduce responsavel por juntar os dados

# Parte 1 da tarefa. Arquivo de saida item1.out

cd ex1
echo Mudando diretorio para:
pwd
echo Iniciando job mapreduce tarefa1
./run.sh
echo Finalizado job mapreduce tarefa1

cd ..
echo Mudando diretorio para:
pwd

# Parte 2 da tarefa. Arquivo de saida item1.out

cd ex2
echo Mudando diretorio para:
pwd
echo Iniciando job mapreduce tarefa2
./run.sh
echo Finalizado job mapreduce tarefa2

cd ..
echo Mudando diretorio para:
pwd