#!/usr/bin/env bash

# Adiciona o arquivo measurements para o hdfs do hadoop
echo Iniciando insercao de measurements no hdfs
hadoop fs -put measurements.txt
echo Finalizada insercao de measurements no hdfs

# Adiciona o arquivo sensor-location para o hdfs do hadoop
echo Iniciando insercao de sensor-location no hdfs
hadoop fs -put sensor-location.txt
echo Finalizada insercao de sensor-location no hdfs

# Cria um novo arquivo que junta as informacoes dos dois arquivos, esse arquivo sera criado no hdfs com o nome measurements-vs-sensor-location
echo Iniciando job mapreduce responsavel por juntar os dados
#./join.sh
hadoop jar /home/bitnami/stack/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.1.0.jar \
    -files join-mapper.py,join-reducer.py \
    -mapper join-mapper.py \
    -reducer join-reducer.py \
    -input measurements.txt \
    -input sensor-location.txt \
    -output measurements-vs-sensor-location
echo Finalizado job mapreduce responsavel por juntar os dados

# Parte 1 da tarefa. Arquivo de saida item1.out

cd ex1
echo Mudando diretorio para:
pwd
echo Iniciando job mapreduce tarefa1
#./run.sh
hadoop jar /home/bitnami/stack/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.1.0.jar \
    -files mapper.py,reducer.py \
    -mapper mapper.py \
    -reducer reducer.py \
    -input measurements-vs-sensor-location \
    -output item1.out
echo Finalizado job mapreduce tarefa1

cd ..
echo Mudando diretorio para:
pwd

# Parte 2 da tarefa. Arquivo de saida item2.out

cd ex2
echo Mudando diretorio para:
pwd
echo Iniciando job mapreduce tarefa2
#./run.sh
hadoop jar /home/bitnami/stack/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.1.0.jar \
    -files mapper.py,reducer.py \
    -mapper mapper.py \
    -reducer reducer.py \
    -input measurements-vs-sensor-location \
    -output item2.out
echo Finalizado job mapreduce tarefa2

cd ..
echo Mudando diretorio para:
pwd

# Parte 3 da tarefa. Arquivo de saida item2.out

cd ex3
echo Mudando diretorio para:
pwd
echo Iniciando job mapreduce tarefa3
#./run.sh
hadoop jar /home/bitnami/stack/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.1.0.jar \
    -files mapper.py,reducer.py \
    -mapper mapper.py \
    -reducer reducer.py \
    -input measurements-vs-sensor-location \
    -output item3.out
echo Finalizado job mapreduce tarefa3

cd ..
echo Mudando diretorio para:
pwd

# Exportando arquivos

hadoop fs -get item1.out/part-00000 item1.out
hadoop fs -get item2.out/part-00000 item2.out
hadoop fs -get item3.out/part-00000 item3.out